# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-clean" do
  version "0.1.10"

  on_macos do
    on_intel do
      sha256 "41c3fd3a7f55a3841f399b36cd7e50e3f66e7854f9afb2b00ec931cc2b56d35f"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53fe251a6417cd64ce39e12e6adebb195206d2b3c9ae707239037ac9bcbce182"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8988212cf4e8798313fb0a3b1e8602b1c81f235975a0977aac4923b8a10e947c"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d95a7e98f693eedd1dc696b21086f05c9474417302eb89256152ac59a1927428"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_linux_arm64.tar.gz"
    end
  end

  name "ai-clean"
  desc "Clean clipboard text from AI CLI tools"
  homepage "https://github.com/TheAndruu/ai-clean"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-clean"
  bash_completion "completions/ai-clean.bash"
  fish_completion "completions/ai-clean.fish"
  zsh_completion "completions/ai-clean.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai-clean"]
    end
  end

  # No zap stanza required

end
