# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-clean" do
  version "0.1.11"

  on_macos do
    on_intel do
      sha256 "6db73933b1a875f31b6b4802388a0861fe4e5e4a4460a8756f968ace7f8c87f5"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0feace8561b5b2db950a9535e51314c487861a182b7494cf1f45118c00dc5fa9"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7c13c91f3304a4b48b9876c2f41c48f37124133aa21de6725012b7ad1858e7a8"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "12ff4c05a5b6522bd50848c22d9570bd6f40fb35d208a782b1ab2c7ad93b8e69"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_linux_arm64.tar.gz"
    end
  end

  name "ai-clean"
  desc "Clean clipboard text from AI CLI tools"
  homepage "https://github.com/TheAndruu/ai-clean"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-clean"
  bash_completion "completions/ai-clean.bash"
  fish_completion "completions/ai-clean.fish"
  zsh_completion "completions/ai-clean.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai-clean"]
    end
  end

  # No zap stanza required

end
