# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-clean" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "53a8e2a2de64eb9e0b2001e8ae3a5a292f409d68fc68b4d1f2b24a29469b6127"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "785b775e3a1de38098626680498c70af6b22fa2acfa5189bf28e133b0b556213"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cabf67b638d3d7cf1d1463895c4fd4b964655f26c5852b1d4e68bf51cb831f99"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e078be423b47e1f6b5d1e04873c7d73dcb95eb8ad232026d4488d757f3b4b2dc"
      url "https://github.com/TheAndruu/ai-clean/releases/download/v#{version}/ai-clean_linux_arm64.tar.gz"
    end
  end

  name "ai-clean"
  desc "Clean clipboard text from AI CLI tools"
  homepage "https://github.com/TheAndruu/ai-clean"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-clean"
  bash_completion "completions/ai-clean.bash"
  fish_completion "completions/ai-clean.fish"
  zsh_completion "completions/ai-clean.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai-clean"]
    end
  end

  # No zap stanza required

end
