# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiClean < Formula
  desc "Clean clipboard text from AI CLI tools"
  homepage "https://github.com/TheAndruu/ai-clean"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheAndruu/ai-clean/releases/download/v0.1.6/ai-clean_darwin_amd64.tar.gz"
      sha256 "10893f98ddb631b03cb5d6b9a14d064505bb34b9dc5b248d9db0616d6efeba1a"

      define_method(:install) do
        bin.install "ai-clean"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheAndruu/ai-clean/releases/download/v0.1.6/ai-clean_darwin_arm64.tar.gz"
      sha256 "b07faac787603f8f902efad0369b1d6d88e4db11fa39fb3d298f8db5c915ec35"

      define_method(:install) do
        bin.install "ai-clean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheAndruu/ai-clean/releases/download/v0.1.6/ai-clean_linux_amd64.tar.gz"
      sha256 "10520a1c18c1e5b10c650df6c3bed38527628d901482d8dbe4f4d82512c08efa"
      define_method(:install) do
        bin.install "ai-clean"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheAndruu/ai-clean/releases/download/v0.1.6/ai-clean_linux_arm64.tar.gz"
      sha256 "d878e11977ffebfa7891d7f9cddc16a5ad8a0c244bac9d0348e6a9010fa3b68c"
      define_method(:install) do
        bin.install "ai-clean"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ai-clean --version")
  end
end
