# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiClean < Formula
  desc "Clean clipboard text from AI CLI tools"
  homepage "https://github.com/TheAndruu/ai-clean"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheAndruu/ai-clean/releases/download/v0.1.8/ai-clean_darwin_amd64.tar.gz"
      sha256 "4b1033aedc3ee4a76f8cb5ab7ad9d74f9eeafb8ca982ee6bcfb05de70bbb80be"

      define_method(:install) do
        bin.install "ai-clean"
        bash_completion.install "completions/ai-clean.bash" => "ai-clean"
        zsh_completion.install "completions/ai-clean.zsh" => "_ai-clean"
        fish_completion.install "completions/ai-clean.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheAndruu/ai-clean/releases/download/v0.1.8/ai-clean_darwin_arm64.tar.gz"
      sha256 "f19551be6c595a8f0afa46ad4050066ecd045fba990d5933bd6b225b47b5005f"

      define_method(:install) do
        bin.install "ai-clean"
        bash_completion.install "completions/ai-clean.bash" => "ai-clean"
        zsh_completion.install "completions/ai-clean.zsh" => "_ai-clean"
        fish_completion.install "completions/ai-clean.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheAndruu/ai-clean/releases/download/v0.1.8/ai-clean_linux_amd64.tar.gz"
      sha256 "ced1fd505597326fde0a771ea2db360417c2be479afd519314921ef076fb170f"
      define_method(:install) do
        bin.install "ai-clean"
        bash_completion.install "completions/ai-clean.bash" => "ai-clean"
        zsh_completion.install "completions/ai-clean.zsh" => "_ai-clean"
        fish_completion.install "completions/ai-clean.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheAndruu/ai-clean/releases/download/v0.1.8/ai-clean_linux_arm64.tar.gz"
      sha256 "ff5bd32d84d7e412a62b53d10465ac2e466042be1b10cc54775086259baef936"
      define_method(:install) do
        bin.install "ai-clean"
        bash_completion.install "completions/ai-clean.bash" => "ai-clean"
        zsh_completion.install "completions/ai-clean.zsh" => "_ai-clean"
        fish_completion.install "completions/ai-clean.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ai-clean --version")
  end
end
